/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 retro.gltf --transform
Author: FishyBusiness (https://sketchfab.com/FishyBusiness)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-78bedd5bc4aa422296181fc28042426b
Title: Retro Computer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/retro-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_5.geometry}
				material={materials.texture3}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_6.geometry}
				material={materials.texture2}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_7.geometry}
				material={materials.texture4}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_8.geometry}
				material={materials.texture6}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_9.geometry}
				material={materials.texture5}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_10.geometry}
				material={materials.texture}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_12.geometry}
				material={materials.texture7}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_14.geometry}
				material={materials.texture8}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_15.geometry}
				material={materials.texture9}
				position={[-0.002, 0, -0.188]}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_21.geometry}
				material={materials.texture10}
				rotation={[-Math.PI, -0.008, -Math.PI]}
			/>
		</group>
	);
}

useGLTF.preload("/retro-transformed.glb");
